### ISSUE TITLE
Nonconsecutive ids in swc morphology

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/MorphIO#259]
Ids `4` and `9` are ignored but I suspect that an error should raise?

Morphology:
```
1 1 0.0 0.0 0.0 0.1 -1
2 1 0.0 0.2 0.0 0.1 1
3 1 0.1 0.1 0.0 0.1 2
4 2 0.0 0.0 0.0 0.853512884994 1
9 2 3.0 6.0 0.0 0.853512884994 1
6 2 -0.230907087225 -0.58831961861 0.257625320211 0.542229087354 5
5 2 1.0 0.0 0.0 0.653512884994 1
7 2 -1.07548305546 -0.79962624501 0.770244808109 0.158341330171 6
```

code:
```python
    from morphio import Morphology

    m = Morphology('test_data/swc/Neuron_nonconsecutive_ids.swc', Option.no_duplicates | Option.nrn_order)
    for sec in m.sections:
        print(sec.points)
```

output:
```
[[ 1.          0.          0.        ]
 [-0.23090708 -0.5883196   0.2576253 ]
 [-1.0754831  -0.79962623  0.77024484]]
```

cc @tomdele , @mgeplf

**Comment by mgeplf** [comment]
Is it possible that 1 is deleted because it's 0 length?
I think 5 gets deleted b/c of the infamous unifurcation deletion - 5 & 6 only have a single child, if I'm reading it right, so they are deleted.

**Comment by asanin-epfl** [comment]
Thank you! I totally forgot about parent ids. With correct parent ids, it is read correctly.

**Comment by mgeplf** [comment]
np; morphologies are, on the face of things, 'simple', however, in practice...much more complicated than one would expect - easy to miss these things.

**Comment by asanin-epfl** [comment]
The problem that in NeuroM v1 this morph raises even with correct parent ids. But thinking generally, nonconsecutive ids is not an error as long as the morphology is read correctly.

**Comment by mgeplf** [comment]
> The problem that in NeuroM v1 this morph raises even with correct parent ids

What error did it raise?

**Comment by asanin-epfl** [comment]
```
Traceback (most recent call last):
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/utils.py", line 193, in load_data
    return _READERS[reader](filename)
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/swc.py", line 56, in read
    return data_wrapper(data[:, [X, Y, Z, R, TYPE, ID, P]], 'SWC', None)
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/datawrapper.py", line 74, in __init__
    self.sections = sections if sections is not None else _extract_sections(data_block)
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/datawrapper.py", line 205, in _extract_sections
    sec.pid = parent_section[sec.ids[0]]
KeyError: 7

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "deleteme.py", line 17, in <module>
    m = load_neuron('test_data/swc/Neuron_nonconsecutive_ids.swc')
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/utils.py", line 116, in load_neuron
    rdw = load_data(handle, reader)
  File "/Users/sanin/workspace/NeuroM-v1/neurom/io/utils.py", line 196, in load_data
    raise RawDataError('Error reading file %s:\n%s' % (filename, str(e))) from e
neurom.exceptions.RawDataError: Error reading file test_data/swc/Neuron_nonconsecutive_ids.swc:
```

**Comment by mgeplf** [comment]
cool, thanks.
I think this may also have happened to https://github.com/BlueBrain/NeuroM/issues/858 which seems to have gotten overlooked, so `NeuromV2` will hopefully fix that too?

**Comment by asanin-epfl** [comment]
Yes, NeuroM v2 will fix those issues.
