### ISSUE TITLE
Failed building of wheels during building of documentation

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/MorphIO#345]
The full log can be seen at https://readthedocs.org/projects/morphio/builds/14720285/. It started 5 days ago. @mgeplf please advice.
```
Failed to build MorphIO

Pip subprocess error:
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/morphio/conda/latest/bin/python /home/docs/checkouts/readthedocs.org/user_builds/morphio/conda/latest/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpsnflxq8d
       cwd: /tmp/pip-req-build-li0b8iq4
 ...
  -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
  CMake Error at /tmp/pip-build-env-a_ep2bk0/overlay/lib/python3.6/site-packages/cmake/data/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found
    version "")
  Call Stack (most recent call first):
    /tmp/pip-build-env-a_ep2bk0/overlay/lib/python3.6/site-packages/cmake/data/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    /tmp/pip-build-env-a_ep2bk0/overlay/lib/python3.6/site-packages/cmake/data/share/cmake-3.21/Modules/FindHDF5.cmake:1001 (find_package_handle_standard_args)
    3rdparty/CMakeLists.txt:1 (find_package)
```

**Comment by mgeplf** [comment]
My guess is that my changes to the build process don't work under conda - a use case I hadn't tried.  It looks like the `pyproject.toml` supplied cmake isn't finding the HDF5 install - I wonder if we could just delete the `pyproject.toml`; in the readthedocs build, and make sure that `cmake` & `ninja` are installed.

**Comment by mgeplf** [comment]
I tried it with the newest conda, and it seems to build fine, I will try some more.

**Comment by asanin-epfl** [comment]
when running on my Mac laptop with previously cleared `build` folder and updated submodules gives:
```
Installing collected packages: MorphIO
  Running setup.py develop for MorphIO
    ERROR: Command errored out with exit status 1:
     command: /Users/sanin/workspace/MorphIO/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sanin/workspace/MorphIO/setup.py'"'"'; __file__='"'"'/Users/sanin/workspace/MorphIO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/sanin/workspace/MorphIO/
    Complete output (71 lines):
    running develop
    running egg_info
    creating MorphIO.egg-info
    writing MorphIO.egg-info/PKG-INFO
    writing dependency_links to MorphIO.egg-info/dependency_links.txt
    writing requirements to MorphIO.egg-info/requires.txt
    writing top-level names to MorphIO.egg-info/top_level.txt
    writing manifest file 'MorphIO.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'COPYING'
    adding license file 'COPYING.LESSER'
    writing manifest file 'MorphIO.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is AppleClang 12.0.0.12000032
    -- The CXX compiler identification is AppleClang 12.0.0.12000032
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    Floating Point Type: float
    -- Found HDF5: /usr/local/Cellar/hdf5/1.12.0_1/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libz.tbd;/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libdl.tbd;/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/lib/libm.tbd (found version "1.12.0")
    -- Found Doxygen: /usr/local/bin/doxygen (found version "1.9.1") found components: doxygen dot
    -- Project 'gsl_lite', package 'gsl-lite' version: '0.38.1'
    -- pybind11 v2.8.0 dev2
    -- Found PythonInterp: /Users/sanin/workspace/MorphIO/venv/bin/python (found version "3.7.9")
    -- Found PythonLibs: /Users/sanin/.pyenv/versions/3.7.9/lib/libpython3.7m.a
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Performing Test HAS_FLTO_THIN
    -- Performing Test HAS_FLTO_THIN - Success
    CMake Error at 3rdparty/CMakeLists.txt:20 (target_include_directories):
      Cannot specify include directories for target "pybind11" which is not built
      by this project.
    
    
    -- Warning: this does not have an effect - use NO_SYSTEM_FROM_IMPORTED if using imported targets
    -- Configuring incomplete, errors occurred!
    See also "/Users/sanin/workspace/MorphIO/build/temp.macosx-10.15-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/sanin/workspace/MorphIO/setup.py", line 98, in <module>
        'setuptools_scm',
      File "/private/var/folders/qy/d2s4f8916yd63kptgvzw2gxmzsmb4j/T/pip-build-env-1nuiuk19/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/qy/d2s4f8916yd63kptgvzw2gxmzsmb4j/T/pip-build-env-1nuiuk19/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/private/var/folders/qy/d2s4f8916yd63kptgvzw2gxmzsmb4j/T/pip-build-env-1nuiuk19/overlay/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/sanin/workspace/MorphIO/setup.py", line 28, in run
        self.build_extension(ext)
      File "/Users/sanin/workspace/MorphIO/setup.py", line 56, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
      File "/Users/sanin/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/Users/sanin/workspace/MorphIO', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/sanin/workspace/MorphIO/morphio', '-DMORPHIO_VERSION_STRING=3.3.1.dev14+g66ae68a.d20210921', '-DMORPHIO_TESTS=OFF', '-DPYTHON_EXECUTABLE=/Users/sanin/workspace/MorphIO/venv/bin/python', '-DHIGHFIVE_EXAMPLES=OFF', '-DHIGHFIVE_UNIT_TESTS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DMorphIO_CXX_WARNINGS=OFF', '-GNinja']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sanin/workspace/MorphIO/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sanin/workspace/MorphIO/setup.py'"'"'; __file__='"'"'/Users/sanin/workspace/MorphIO/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
You should consider upgrading via the '/Users/sanin/workspace/MorphIO/venv/bin/python -m pip install --upgrade pip' command.
```
