### ISSUE TITLE
Cannot install morphio using pip on macos with M1 and Python3.10

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/MorphIO#446]
```
bb-gl2300cjgw:bin abdellah$ ./python3.10 -m pip install morphio
Collecting morphio
 Using cached MorphIO-3.3.4.tar.gz (508 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Installing backend dependencies ... done
 Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.1 in /Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages (from morphio) (1.24.3)
Building wheels for collected packages: morphio
 Building wheel for morphio (pyproject.toml) ... error
 error: subprocess-exited-with-error
 × Building wheel for morphio (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─> [84 lines of output]
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.00-arm64-cpython-310
    creating build/lib.macosx-11.00-arm64-cpython-310/morphio
    copying morphio/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio
    creating build/lib.macosx-11.00-arm64-cpython-310/morphio/mut
    copying morphio/mut/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio/mut
    creating build/lib.macosx-11.00-arm64-cpython-310/morphio/vasculature
    copying morphio/vasculature/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio/vasculature
    running build_ext
    -- The C compiler identification is AppleClang 14.0.0.14000029
    -- The CXX compiler identification is AppleClang 14.0.0.14000029
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    Floating Point Type: float
    CMake Error at /private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found
     version "")
    Call Stack (most recent call first):
     /private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
     /private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindHDF5.cmake:1001 (find_package_handle_standard_args)
     3rdparty/CMakeLists.txt:1 (find_package)
    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
     File "/Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
     File "/Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
     File "/Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
     File "<string>", line 69, in <module>
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
     File "/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
     File "<string>", line 28, in run
     File "<string>", line 56, in build_extension
     File "/Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-install-35j0f1g1/morphio_6f2d72cf91ee4f8c90c28d6061b0a66b', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-install-35j0f1g1/morphio_6f2d72cf91ee4f8c90c28d6061b0a66b/build/lib.macosx-11.00-arm64-cpython-310/morphio', '-DMORPHIO_VERSION_STRING=3.3.4', '-DMORPHIO_TESTS=OFF', '-DPYTHON_EXECUTABLE=/Users/abdellah/Downloads/nmv/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/bin/python3.10', '-DHIGHFIVE_EXAMPLES=OFF', '-DHIGHFIVE_UNIT_TESTS=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DMorphIO_CXX_WARNINGS=OFF', '-GNinja']' returned non-zero exit status 1.
    [end of output]
 note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for morphio
Failed to build morphio
ERROR: Could not build wheels for morphio, which is required to install pyproject.toml-based projects
```

**Comment by mgeplf** [comment]
This seems relevant; do you have hdf5 development libraries installed?
```
CMake Error at /private/var/folders/vs/ryptqcjs5ml6cfr542dk0915g73tv_/T/pip-build-env-18hfyec1/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found
     version "")
```

**Comment by marwan-abdellah** [comment]
Yes. I have alreadt tries to install morphio on my intel based macos and it works. The issue only happens on the M1 based mac.

**Comment by mgeplf** [comment]
> Yes. I have already tried to install morphio on my intel based macos and it works. 

Are you compiling it, or using the wheels?
If it's compilation, you'll also need the hdf5 libraries installed.

We can try turning on, assuming it's available with the Github actions, an arm builder for wheels, and see if it works that way.

**Comment by 1uc** [comment]
Since I recently wrote it up for something else, I'll share it here. This a dummy file for checking if HDF5 works:
```
#include <hdf5.h>

int main() {
  auto file = H5Fcreate("foo.h5", H5F_ACC_EXCL, H5P_DEFAULT, H5P_DEFAULT);
  H5Fclose(file);
  return 0;
}
```
call it `dummy.cpp`. Then use this `CMakeLists.txt` to compile it:
```
cmake_minimum_required(VERSION 3.19)
project(Dummy)

find_package(HDF5 REQUIRED)
add_executable(dummy dummy.cpp)
target_link_libraries(dummy HDF5::HDF5)
```
Then you call
```
cmake -B build .
cmake --build build
```
This would allow you decide if the issue is in MorphIO's CMake code specifically or more generally related to finding HDF5.

**Comment by mgeplf** [comment]
@marwan-abdellah Any luck trying the suggestion above?

**Comment by githubfzq** [comment]
I have the same issue on MacOS with M1, but using Ubuntu docker image with Python 3.11.

**Comment by githubfzq** [comment]
> I have the same issue on MacOS with M1, but using Ubuntu docker image with Python 3.11.

Installing an hdf5 apt package works for me:
```
sudo apt-get install libhdf5-dev
```

**Comment by marwan-abdellah** [comment]
@twheatcroft07 Not that I know of. I cannot still install it on the new M1 chips.

**Comment by mgeplf** [comment]
@marwan-abdellah have you tried what @1uc suggested?

**Comment by marwan-abdellah** [comment]
@mgeplf I tested it and it works. 

```
 $ cmake ..
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found HDF5: /opt/local/lib/libhdf5.dylib;/opt/local/lib/libaec/lib/libsz.dylib;/opt/local/lib/libz.dylib;/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libdl.tbd;/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libm.tbd (found version "1.14.1-2")
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/abdellah/tmp/hdf/build
[  8:50PM ]  [ abdellah@Marwans-MacBook-Pro:~/tmp/hdf/build(system: ruby 2.6.10p210) ]
 $ make
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
/Users/abdellah/tmp/hdf/test.cpp:4:3: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
  auto file = H5Fcreate("foo.h5", H5F_ACC_EXCL, H5P_DEFAULT, H5P_DEFAULT);
  ^
1 warning generated.
[100%] Linking CXX executable test
[100%] Built target test
```

**Comment by marwan-abdellah** [comment]
@mgeplf Nonetheless, I tried to compile MorphIO myself on the M1 mac, I got the following issues: 

[```
  8:53PM ]  [ abdellah@Marwans-MacBook-Pro:~/tmp/MorphIO/build(master✔)(system: ruby 2.6.10p210) ]
 $ cmake ..
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Floating Point Type: float
-- Found HDF5: /opt/local/lib/libhdf5.dylib;/opt/local/lib/libaec/lib/libsz.dylib;/opt/local/lib/libz.dylib;/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libdl.tbd;/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libm.tbd (found version "1.14.1-2")
CMake Error at 3rdparty/CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /Users/abdellah/tmp/MorphIO/3rdparty/HighFive

  does not contain a CMakeLists.txt file.


CMake Error at 3rdparty/CMakeLists.txt:9 (target_include_directories):
  Cannot specify include directories for target "HighFive" which is not built
  by this project.


CMake Error at 3rdparty/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /Users/abdellah/tmp/MorphIO/3rdparty/GSL_LITE

  does not contain a CMakeLists.txt file.


CMake Error at 3rdparty/CMakeLists.txt:13 (target_include_directories):
  Cannot specify include directories for target "gsl-lite" which is not built
  by this project.


CMake Error at 3rdparty/CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /Users/abdellah/tmp/MorphIO/3rdparty/ghc_filesystem

  does not contain a CMakeLists.txt file.


CMake Error at binds/python/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /Users/abdellah/tmp/MorphIO/binds/python/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at binds/python/CMakeLists.txt:5 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
```

**Comment by mgeplf** [comment]
> CMake Error at 3rdparty/CMakeLists.txt:8 (add_subdirectory):

That looks like the submodules havne't been pulled:
```
git submodule update --init --recursive
```
Should fix that problem.

**Comment by marwan-abdellah** [comment]
@mgeplf So I managed to compile it on my M1 mac now. But why is it still failing when I pip it then?

**Comment by marwan-abdellah** [comment]
I gave it another try with Python3.9 and it is installable. I can confirm 

```
 $ pip3 install morphio
Defaulting to user installation because normal site-packages is not writeable
Collecting morphio
  Using cached MorphIO-3.3.5.tar.gz (576 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.1 in /Users/abdellah/Library/Python/3.9/lib/python/site-packages (from morphio) (1.25.0)
Building wheels for collected packages: morphio
  Building wheel for morphio (pyproject.toml) ... done
  Created wheel for morphio: filename=MorphIO-3.3.5-cp39-cp39-macosx_13_0_universal2.whl size=602848 sha256=6b0ce9f9f6604aa90084dfff85570958286240d90cc46659931b86d63a5d21a3
  Stored in directory: /Users/abdellah/Library/Caches/pip/wheels/fe/14/65/2444eb52f7d64ba38e5563a81fbdf8a913b1319248e730419f
Successfully built morphio
Installing collected packages: morphio
Successfully installed morphio-3.3.5
[ 11:50AM ]  [ abdellah@Marwans-MacBook-Pro:~/tmp/MorphIO/build/binds/python/pybind11(master✔)(system: ruby 2.6.10p210) ]
 $ pip3 --version
pip 23.1.2 from /Users/abdellah/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
```

**Comment by mgeplf** [comment]
Since it's not finding `Python.h`, but
```
-isystem /Applications/Blender.app/Contents/Resources/3.5/python/include/python3.10 
```

Is being used for python, I wonder if it's how Blender packages its python installation.  Does that directory have a `Python.h` file?

**Comment by marwan-abdellah** [comment]
@mgeplf I will try it with the system Python 3.10 then.

**Comment by marwan-abdellah** [comment]
@mgeplf I could also install it using the system python. 

```
 $ python3.10 -m pip install morphio
Defaulting to user installation because normal site-packages is not writeable
Collecting morphio
  Using cached MorphIO-3.3.5.tar.gz (576 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.14.1 in /Users/abdellah/Library/Python/3.10/lib/python/site-packages (from morphio) (1.25.0)
Building wheels for collected packages: morphio
  Building wheel for morphio (pyproject.toml) ... done
  Created wheel for morphio: filename=MorphIO-3.3.5-cp310-cp310-macosx_13_0_arm64.whl size=602763 sha256=90749f6f01cd7e0c6371fefd8c0b7128a966e6db3bacc6517a3c0bd6ae1efbc1
  Stored in directory: /Users/abdellah/Library/Caches/pip/wheels/5b/8d/96/5175a7ffe58f3207a45b03eb81877e5c7dc69fb6c2ba28f7cb
Successfully built morphio
Installing collected packages: morphio
Successfully installed morphio-3.3.5
```

**Comment by marwan-abdellah** [comment]
> /Applications/Blender.app/Contents/Resources/3.5/python/include/python3.10
The directory does not have any Python.h file. 

[ 12:05PM ]  [ abdellah@tsf-500-wpa-3-255:/Applications/Blender.app/Contents/Resources/3.5/python/include/python3.10(system: ruby 2.6.10p210) ]
 $ ls
pyconfig.h

**Comment by marwan-abdellah** [comment]
That's a limitation in Blender then [https://github.com/pypa/setuptools/issues/3589]. I would then close the ticket. 
Thanks @mgeplf

**Comment by mgeplf** [comment]
No problem, glad we could figure it out.
If/when I find time, I will try and have the build process create wheels, which would also probably solve this problem.
